---
- name: Install mc on Debian-based systems
  hosts: all
    # Run as sudo
  tasks:
    - name: Install mc
      apt:
        name: mc
        state: present
        update_cache: yes
  become: yes
